<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="user-scalable = yes" />
    <meta content='width=device-width, minimum-scale=1' name='viewport'>
	<title>Pegasus</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

	<link rel="stylesheet" href="<?php echo get_bloginfo('template_directory'); ?>/style.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <!-- Generated by http://www.favicomatic.com -->
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="<?php echo get_bloginfo('template_directory'); ?>/img/favicon/apple-touch-icon-57x57.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-114x114.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-72x72.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-144x144.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-60x60.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-120x120.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-76x76.png?v=1556272733862" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/apple-touch-icon-152x152.png?v=1556272733862" />
    <link rel="icon" type="image/png" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/favicon-196x196.png?v=1556272733862" sizes="196x196" />
    <link rel="icon" type="image/png" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/favicon-96x96.png?v=1556272733862" sizes="96x96" />
    <link rel="icon" type="image/png" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/favicon-32x32.png?v=1556272733862" sizes="32x32" />
    <link rel="icon" type="image/png" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/favicon-16x16.png?v=1556272733862" sizes="16x16" />
    <link rel="icon" type="image/png" href="<?php echo get_bloginfo('template_directory'); ?>/favicon/favicon-128.png?v=1556272733862" sizes="128x128" />
    <meta name="application-name" content="&nbsp;"/>
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <meta name="msapplication-TileImage" content="<?php echo get_bloginfo('template_directory'); ?>/favicon/mstile-144x144.png?v=1556272733862" />
    <meta name="msapplication-square70x70logo" content="<?php echo get_bloginfo('template_directory'); ?>/favicon/mstile-70x70.png?v=1556272733862" />
    <meta name="msapplication-square150x150logo" content="<?php echo get_bloginfo('template_directory'); ?>/favicon/mstile-150x150.png?v=1556272733862" />
    <meta name="msapplication-wide310x150logo" content="<?php echo get_bloginfo('template_directory'); ?>/favicon/mstile-310x150.png?v=1556272733862" />
    <meta name="msapplication-square310x310logo" content="<?php echo get_bloginfo('template_directory'); ?>/favicon/mstile-310x310.png?v=1556272733862" />
	<!--[if IE 9]>
		<link rel="stylesheet" href="css/ie9.css">
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<div class="container">
        <header class="header">
            <picture class="header-logo">
              <source srcset="<?php echo get_bloginfo('template_directory'); ?>/img/logo_pegasus.png 1x, <?php echo get_bloginfo('template_directory'); ?>/img/retina/logo_pegasus@2x.png 2x">
              <img src="<?php echo get_bloginfo('template_directory'); ?>/img/logo_pegasus.png" alt="logo">
            </picture>
            <div class="wrapper header-wrapper">
                <div class="header__phone">
                    <div class="hotline">
                        <a href="tel:+442077198816" class="hotline__number">+44 20 7719 8816</a>
                        <p class="hotline__text">Круглосуточно</p>
                        <hr class="decorate-line decorate-line_hotline"/>
                    </div>
                    <div class="phone-messenger phone-messenger_header_position">
                        <a href="tel:+447771007676" class="phone-messenger__number">+44 777 100 7676</a>
                        <p class="phone-messenger__text">Viber & WhatsApp</p>
                        <hr class="decorate-line decorate-line_messenger"/>
                    </div>
                </div>
                <div class="header__book">
                    <button class="btn  btn-tariff">
                        <span class="btn__text">Узнать тариф</span>
                    </button>
                    <button class="btn btn-book" >
                        <span class="btn__text ">Сделать заказ</span>
                    </button>
                </div>
            </div>
        </header>        <main>
            <section class="page-menu">
                <h2>Main-menu</h2>
                <div class="wrapper-nav">
                    <?php wp_nav_menu( array( 'theme_location' => 'header-menu' ) ); ?>
                </div>
            </section>            
            <section class="breadcrumbs">
                <h2>breadcrumbs</h2>
                <div class="breadcrumbs-wrapper">
                    <div class="breadcrumbs-container">
                    <p class="breadcrumbs__item breadcrumbs__item_main">Главная</p>
                    <p class="breadcrumbs__item breadcrumbs__item_events">События</p>
                    <p class="breadcrumbs__item breadcrumbs__item_border">Экскурсии</p>
                    </div>
                </div>
            </section>            <section class="tours-description">
                <h2>Tours description</h2>
                <div class="wrapper">
                    <div class="tours-container">
                        <p class="tours-description__header"><?php bloginfo('name'); ?></p>
                        <div>
                            <hr class="decorate-line-tours decorate-line-tours_before"/>
                            <p class="tours-description__header-tours"><?php bloginfo('description'); ?></p>
                            <?php
                                if ( is_active_sidebar( 'title-paragraph-1' ) ) {
                            ?>
                            <div>
                                <?php dynamic_sidebar( 'title-paragraph-1' ); ?>
                            </div>
                            <?php } ?>
                            <hr class="decorate-line-tours decorate-line-tours_after"/>
                        </div>
                    </div>
                </div>
            </section>            <section class="tours">
                <h2>Tours</h2>
                <div class="wrapper">
                    <div class="tours-wrap">
                        <?php
                            if ( have_posts() ) : while ( have_posts() ) : the_post();
                                get_template_part( 'excursion', get_post_format() );
                            endwhile; endif;
                        ?>
                    </div>
                </div>
            </section>       
             </main>
        <footer class="footer">
            <div class="background-city"></div>
            <div class="background-city_black"></div>
            <div class="footer-container">
                <div class="footer-flex-container">
                <hr class="decorate-line-footer decorate-line-footer_position_car-wp"/>
                <hr class="decorate-line-footer decorate-line-footer_position_service-wp"/>
                <hr class="decorate-line-footer decorate-line-footer_position_about-wp"/>
                        <?php wp_nav_menu( array( 'theme_location' => 'extra-menu' ) ); ?>
                    <div class="footer-column-4">
                        <button class="btn btn-footer" >
                            <span class="btn__text ">Сделать заказ</span>
                        </button>
                        <button class="btn  btn-footer">
                            <span class="btn__text">Узнать тариф</span>
                        </button>
                        <div class="footer__phone">
                            <div class="hotline hotline_footer_position">
                                <a href="tel:+442077198816" class="hotline__number hotline__number_color_white">+44 20 7719 8816</a>
                                <p class="hotline__text hotline__text_color_white">Круглосуточно</p>
                            </div>
                            <div class="phone-messenger phone-messenger_footer_position">
                                <a href="tel:+447771007676" class="phone-messenger__number phone-messenger__number_footer phone-messenger__number_color_white">+44 777 100 7676</a>
                                <p class="phone-messenger__text phone-messenger__text_color_white">Viber & WhatsApp</p>
                            </div>
                            <div class="social-btn">
                                <a href="https://www.instagram.com" class="fab fa-instagram"></a>
                                <a href="https://www.facebook.com" class="fab fa-facebook"></a>
                                <a href="https://accounts.google.com" class="fab fa-google-plus-square"></a>
                                <a href="#" class="fab fa-linkedin"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <p class="copyright">2010-2018 &copy;Pegasus Luxury Services Ltd. Company Number:08104782. PCO-Operator Licence:0086810101. All rights reserved.</p>
            </div>
        </footer>
	</div>
	<script src="<?php echo get_bloginfo('template_directory'); ?>/js/plugins.min.js"></script>
	<script src="<?php echo get_bloginfo('template_directory'); ?>/js/app.js?v=1556272733862"></script>
</body>
</html>


